### ISSUE TITLE
Separate out spec file eslint settings

### ISSUE THREAD

**Issue by cwkingjr** [charwking/gift-exchange-web#26]
On another note, it might be nice to have separate rules for our testing code vs production code. For example, our test code can contain globals like describe, it, and inject, but our production code shouldn't. It's definitely a "nice to have" -- so we don't have to worry about it immediately.

**Comment by charwking** [comment]
I wonder if it's possible to create two eslint grunt tasks, one for tests that reference one config file, and other for prod code that references a second config file -- this may allow us to keep the tests close to the code, but have separate settings for the types of code.

**Comment by cwkingjr** [comment]
I don't see a way to do this, at least using grunt-eslint. For eslint-cli, you can specify a config file with a -c option, but that's not carried through to the grunt-eslint code. The standard way, according to the ESLint docs is to place tests in a tests folder and place a second (supplemental) .eslintrc file there with the test params.

**Comment by charwking** [comment]
It looks like [gruntify-eslint](https://github.com/gyandeeps/gruntify-eslint) _might_ work, where tests are "nodeFiles" and prod code is "browserFiles".

I can poke at this one and see if I can figure it out.

I'd rather have a single lint configuration that followed as closely as possible to our browser-code guidelines and leave the tests in place with the source files than have to maintain two parallel directories in order to split out the tests.

**Comment by cwkingjr** [comment]
Fixed by #28
